#!/usr/bin/env bash
# Generate the scratch KMP target used to test `install.sh --adopt`.
#
# The fixture is a deliberately ORDINARY Kotlin Multiplatform app: Compose
# Multiplatform, Koin and Ktor, its own version catalog, its own package prefix,
# and no KMPilot anything. Adopt-mode must work on a repo it has never seen.
#
# It is generated rather than committed so the test is repeatable and the
# fixture never drifts into the template's shape by accident. Only this script
# lives in the repo (scripts/ is stripped by install.sh and is not delivered by
# update.sh, so it stays upstream-only).
#
# Usage:
#   scripts/make-adopt-target.sh [target-dir] [--force]
#
#   target-dir  default: ~/KMPProjects/adopt-target
#   --force     regenerate over an existing fixture (only ever deletes a
#               directory carrying the .adopt-target-fixture marker)
#
# Deliberate differences from KMPilot, each one exercising a detection path:
#   • module names        app/ + shared/         (not androidApp/ + composeApp/)
#   • rootProject.name    AcmeNotes              (drives the generated-resources package)
#   • package prefix      com.acme.notes         (three segments, not one)
#   • version catalog     its own alias naming   (kmpilotLibs must not collide)
#   • root build.gradle   no allprojects{} conventions at all — vendored core
#                         modules must configure their own compileSdk/minSdk
#   • targets             android + ios only     (no desktop in the app module)
#
# Not generated: an iosApp Xcode project. Adopt-mode never writes into one, and
# the phase's exit criteria are `assembleDebug` + `archTest`, both Android/JVM.

set -euo pipefail

TARGET="${HOME}/KMPProjects/adopt-target"
FORCE=no
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=yes ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        -*) echo "Error: unknown argument '$arg'" >&2; exit 1 ;;
        *)  TARGET="$arg" ;;
    esac
done

NAME="AcmeNotes"
PKG="com.acme.notes"
PKG_PATH="${PKG//.//}"
MARKER=".adopt-target-fixture"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KMPILOT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

command -v git >/dev/null 2>&1 || { echo "Error: git is required" >&2; exit 1; }

if [[ -e "$TARGET" ]]; then
    if [[ "$FORCE" != "yes" ]]; then
        echo "Error: '$TARGET' already exists. Pass --force to regenerate it." >&2
        exit 1
    fi
    # Only ever delete something this script created.
    if [[ ! -f "$TARGET/$MARKER" ]]; then
        echo "Error: '$TARGET' exists but has no $MARKER marker — refusing to delete it." >&2
        exit 1
    fi
    echo "→ Removing existing fixture at $TARGET"
    rm -rf "$TARGET"
fi

echo "→ Generating $NAME fixture at $TARGET"
mkdir -p "$TARGET"
cd "$TARGET"

mkdir -p "app/src/main/kotlin/${PKG_PATH}/android"
mkdir -p "shared/src/commonMain/kotlin/${PKG_PATH}"/{data,di,notes}
mkdir -p "shared/src/androidMain/kotlin/${PKG_PATH}"
mkdir -p "shared/src/iosMain/kotlin/${PKG_PATH}"
mkdir -p gradle/wrapper

cat > "$MARKER" <<'EOF'
Generated by KMPilot's scripts/make-adopt-target.sh — a disposable test fixture
for `install.sh --adopt`. Safe to delete. Regenerate with --force.
EOF

# ── settings ────────────────────────────────────────────────────────────────
cat > settings.gradle.kts <<'EOF'
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AcmeNotes"

include(":app")
include(":shared")
EOF

# ── root build: plugin declarations ONLY, no shared conventions ─────────────
cat > build.gradle.kts <<'EOF'
// Deliberately convention-free: every module configures its own compileSdk,
// minSdk and JVM target. Anything vendored in here has to stand on its own.
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidKmpLibrary) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinSerialization) apply false
}
EOF

cat > gradle.properties <<'EOF'
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.caching=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M
android.useAndroidX=true
EOF

# ── the target's OWN version catalog, in its own naming style ───────────────
# Alias names differ from KMPilot's on purpose (androidx-activityCompose vs
# activityCompose, ktor-json vs ktor-serialization-kotlinx-json, …) so that a
# merge-into-libs strategy would collide and the separate kmpilotLibs catalog
# demonstrably does not.
cat > gradle/libs.versions.toml <<'EOF'
[versions]
agp = "9.2.1"
kotlin = "2.4.0"
composeMultiplatform = "1.11.1"
composeMaterial3 = "1.9.0"
koin = "4.2.1"
ktor = "3.5.0"
kotlinxSerializationJson = "1.11.0"
lifecycle = "2.10.0"
navigationCompose = "2.9.2"
androidxActivityCompose = "1.13.0"

android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }

lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
EOF

# ── app module (Android entry point) ────────────────────────────────────────
cat > app/build.gradle.kts <<'EOF'
plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

android {
    namespace = "com.acme.notes.android"
    compileSdk =
        libs.versions.android.compileSdk
            .get()
            .toInt()

    defaultConfig {
        applicationId = "com.acme.notes"
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()
        targetSdk =
            libs.versions.android.targetSdk
                .get()
                .toInt()
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
}

dependencies {
    implementation(project(":shared"))
    implementation(libs.androidx.activity.compose)
    implementation(libs.koin.android)
}
EOF

cat > app/src/main/AndroidManifest.xml <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:name="com.acme.notes.android.NotesApplication"
        android:allowBackup="true"
        android:label="Acme Notes"
        android:supportsRtl="true"
        android:theme="@android:style/Theme.Material.Light.NoActionBar">
        <activity
            android:name="com.acme.notes.android.MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
EOF

cat > "app/src/main/kotlin/${PKG_PATH}/android/MainActivity.kt" <<'EOF'
package com.acme.notes.android

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import com.acme.notes.App

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { App() }
    }
}
EOF

cat > "app/src/main/kotlin/${PKG_PATH}/android/NotesApplication.kt" <<'EOF'
package com.acme.notes.android

import android.app.Application
import com.acme.notes.initKoin
import org.koin.android.ext.koin.androidContext

class NotesApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        initKoin { androidContext(this@NotesApplication) }
    }
}
EOF

# ── shared module (KMP + Compose Multiplatform) ─────────────────────────────
cat > shared/build.gradle.kts <<'EOF'
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

kotlin {
    android {
        namespace = "com.acme.notes.shared"
        compileSdk =
            libs.versions.android.compileSdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.lifecycle.viewmodel)
            implementation(libs.lifecycle.runtime.compose)
            implementation(libs.navigation.compose)

            api(libs.koin.core)
            implementation(libs.koin.compose)

            implementation(libs.ktor.core)
            implementation(libs.ktor.negotiation)
            implementation(libs.ktor.json)
            implementation(libs.kotlinx.serialization.json)
        }

        androidMain.dependencies {
            implementation(libs.ktor.okhttp)
            implementation(libs.koin.android)
        }

        iosMain.dependencies {
            implementation(libs.ktor.darwin)
        }
    }
}
EOF

cat > "shared/src/commonMain/kotlin/${PKG_PATH}/App.kt" <<'EOF'
package com.acme.notes

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.acme.notes.notes.NoteListRoute
import com.acme.notes.notes.NoteListScreen

@Composable
fun App() {
    MaterialTheme {
        val navController = rememberNavController()
        NavHost(
            navController = navController,
            startDestination = NoteListRoute,
        ) {
            composable<NoteListRoute> { NoteListScreen() }
        }
    }
}
EOF

cat > "shared/src/commonMain/kotlin/${PKG_PATH}/initKoin.kt" <<'EOF'
package com.acme.notes

import com.acme.notes.di.appModule
import org.koin.core.context.startKoin
import org.koin.dsl.KoinAppDeclaration

fun initKoin(appDeclaration: KoinAppDeclaration = {}) {
    startKoin {
        appDeclaration()
        modules(
            appModule,
        )
    }
}
EOF

cat > "shared/src/commonMain/kotlin/${PKG_PATH}/di/AppModule.kt" <<'EOF'
package com.acme.notes.di

import com.acme.notes.data.NotesApi
import io.ktor.client.HttpClient
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json
import org.koin.dsl.module

val appModule =
    module {
        single {
            HttpClient {
                install(ContentNegotiation) {
                    json(Json { ignoreUnknownKeys = true })
                }
            }
        }
        single { NotesApi(get()) }
    }
EOF

cat > "shared/src/commonMain/kotlin/${PKG_PATH}/data/NotesApi.kt" <<'EOF'
package com.acme.notes.data

import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import kotlinx.serialization.Serializable

@Serializable
data class Note(
    val id: String,
    val title: String,
)

/**
 * Plain Ktor call, no Either and no Result wrapper — this is a pre-KMPilot
 * codebase, so the compatibility report should list the missing pieces.
 */
class NotesApi(
    private val client: HttpClient,
) {
    suspend fun notes(): List<Note> = client.get("https://api.example.com/notes").body()
}
EOF

cat > "shared/src/commonMain/kotlin/${PKG_PATH}/notes/NoteListScreen.kt" <<'EOF'
package com.acme.notes.notes

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import kotlinx.serialization.Serializable

@Serializable
object NoteListRoute

@Composable
fun NoteListScreen() {
    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.Center,
    ) {
        Text("Acme Notes")
    }
}
EOF

cat > "shared/src/iosMain/kotlin/${PKG_PATH}/MainViewController.kt" <<'EOF'
package com.acme.notes

import androidx.compose.ui.window.ComposeUIViewController

fun mainViewController() = ComposeUIViewController { App() }
EOF

# ── gradle wrapper (borrowed from KMPilot — same toolchain, not KMPilot code) ─
cp "$KMPILOT_ROOT/gradlew" "$KMPILOT_ROOT/gradlew.bat" .
cp "$KMPILOT_ROOT/gradle/wrapper/gradle-wrapper.jar" \
   "$KMPILOT_ROOT/gradle/wrapper/gradle-wrapper.properties" gradle/wrapper/
chmod +x gradlew

# Android SDK location — reuse whatever this machine already has configured.
if [[ -f "$KMPILOT_ROOT/local.properties" ]] && grep -q '^sdk.dir=' "$KMPILOT_ROOT/local.properties"; then
    grep '^sdk.dir=' "$KMPILOT_ROOT/local.properties" > local.properties
elif [[ -n "${ANDROID_HOME:-}" ]]; then
    echo "sdk.dir=${ANDROID_HOME}" > local.properties
else
    echo "⚠  No Android SDK path found — write local.properties (sdk.dir=…) by hand." >&2
fi

cat > .gitignore <<'EOF'
*.iml
.gradle
.kotlin
/local.properties
/.idea
.DS_Store
build/
captures/
.externalNativeBuild
.cxx
xcuserdata/
EOF

cat > README.md <<'EOF'
# AcmeNotes

A small Kotlin Multiplatform app (Compose Multiplatform, Koin, Ktor).

```bash
./gradlew assembleDebug
```

- `app/` — Android entry point
- `shared/` — shared KMP + Compose Multiplatform code
EOF

# ── git init: adopt-mode refuses to run on a dirty tree, so start clean ─────
git init --quiet
git add -A
git -c user.email=fixture@local -c user.name=fixture commit --quiet \
    -m "AcmeNotes: initial Compose Multiplatform app"

echo "✓ Fixture ready at $TARGET"
echo
echo "Next:"
echo "  cd $TARGET && ./gradlew assembleDebug"
echo "  bash $KMPILOT_ROOT/install.sh --adopt --dry-run"
echo
if [[ -n "${http_proxy:-}" ]]; then
    echo "Note: this shell has http_proxy set. The JVM ignores it, so Gradle cannot"
    echo "      resolve anything not already cached. Pass the proxy as system"
    echo "      properties instead: ./gradlew -Dhttps.proxyHost=… -Dhttps.proxyPort=… …"
fi
